#*!
#* \file
#* \brief Rakefile foo
#*
#* Copyright of Link Motion Ltd. All rights reserved.
#*
#* Contact: info@link-motion.com
#*
#* \author Niko Vähäsarja <niko.vahasarja@nomovok.com>
#*
#* any other legal text to be defined later
#*


require 'rake/testtask'
require 'rubygems'
require 'rubygems/package_task'
require 'fileutils'

logspec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.license = 'Copyright of Link Motion Ltd. All rights reserved.'
  s.name = 'cansimng'
  s.version = '0.39.1'
  s.author = 'Link Motion Ltd'
  s.email = 'info@link-motion.com'
  s.homepage = 'http://link-motion.com'
  s.summary = 'CanSimNG bindings'
  s.description = s.summary + '.'
  # Ensure that everything is listed.
  s.files = FileList['lib/cansimng.rb',
                     'lib/cansimng_syncstate.rb',
                     'lib/cansimng_demosequencer.rb',
                     'bin/can-simulator-ng'].to_a
  s.has_rdoc = false

end

Gem::PackageTask.new(logspec) do |pkg|
  pkg.gem_spec = logspec
  pkg.need_tar = true
end

task :default do |_t|
  puts 'Supported tasks: gem'
end

file 'bin/can-simulator-ng' => '../build/cli/can-simulator-ng' do |_t|
  mkdir_p 'bin'
  cp _t.prerequisites.first, _t.name
end
