#*!
#* \file
#* \brief Rakefile foo
#*
#* Copyright of Link Motion Ltd. All rights reserved.
#*
#* Contact: info@link-motion.com
#*
#* \author Niko Vähäsarja <niko.vahasarja@nomovok.com>
#*
#* any other legal text to be defined later
#*


require 'rake/testtask'
require 'rubygems'
require 'rubygems/package_task'
require 'fileutils'

logspec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.license = 'Copyright of Link Motion Ltd. All rights reserved.'
  s.name = 'audio_test_tool'
  s.version = '0.0.1'
  s.author = 'Link Motion Ltd'
  s.email = 'info@link-motion.com'
  s.homepage = 'http://www.link-motion.com'
  s.summary = 'Audio Testing tool'
  s.description = s.summary + '.'
  # Ensure that everything is listed.
  s.files = ['lib/audio_test_tool.rb',
             'analyzers/thdn.m']
  s.has_rdoc = false

end

Gem::PackageTask.new(logspec) do |pkg|
  pkg.gem_spec = logspec
  pkg.need_tar = true
end

task :default do |_t|
  puts 'Supported tasks: gem'
end

directory 'analyzers'

rule '.m' => ['analyzers'] do |_t|
  cp "../#{_t.name}", "#{_t.name}"
end
