#!/bin/bash
set -e
# Set this to build steps in qt creator.
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@link-motion.com>
# (C) Link Motion Oy

PROJECT_NAME=$1
SSH_IP=$2
SSH_OPTS=$3

if [[ -z ${SSH_IP} ]]; then
  SSH_IP="10.0.0.30"
fi

if [[ ! -z ${SSH_OPTS} ]]; then
  SSH_OPTS="-p ${SSH_OPTS}"
fi

if [ -z ${PROJECT_NAME} ]; then
  echo "You need to pass %{CurrentProject:Name} to build arguments."
  exit 1
fi

SOURCE_VERSION=`cat ${PROJECT_NAME}.spec | grep "Version:" | grep -o '[0-9]\+.[0-9]\+.[0-9]\+'`
SOURCE_PACKAGENAME=`cat ${PROJECT_NAME}.spec | grep "Name:" | sed "s/Name://g" | grep -o "[a-zA-Z0-9_-]\+"`
SOURCE_PACKAGES=`cat ${PROJECT_NAME}.spec | grep "%package" | sed "s/%package//g"| grep -o "[a-zA-Z0-9_-]\+"|tr '\n' ' '`
PACKAGE_NAME=${PROJECT_NAME}.*${SOURCE_VERSION}*.rpm

PACKAGES=""
for PACKAGE in ${SOURCE_PACKAGES}; do
  PACKAGES="${PACKAGES} ${SOURCE_PACKAGENAME}-${PACKAGE}"
done

ssh $SSH_OPTS system@${SSH_IP} << EOF
  mkdir -p /home/system/src/${PROJECT_NAME}
EOF

echo "Precleaning the source tree.."
if [[ -f Makefile ]]; then
  make distclean
fi
echo "..cleaned!"
echo
echo "Transfer the source tree to target.."
rsync --exclude=".git" --exclude=".tmp" -e "ssh ${SSH_OPTS}" -avz --delete --rsync-path=/altdata/devel/bin/rsync . system@${SSH_IP}:/home/system/src/${PROJECT_NAME} 
echo "..transfer complete!"
echo
echo "Build source on target.."
ssh ${SSH_OPTS} system@${SSH_IP} << EOF
  sudo rpm --nodeps -e ${SOURCE_PACKAGENAME}
  sudo rpm --nodeps -e ${PACKAGES}
  cd /home/system/src/${PROJECT_NAME}
  qmake -r
  make
EOF
echo "..source has been built!"
echo
